# libraries used in package

library(fields)
library(Matrix)
library(GpGp)
library(invgamma)
library(scoringRules)
library(mvnfast)
library(DescTools)
library(matrixStats)
library(truncnorm)
library(MASS)
library(lattice)
library(inline)
library(parallel)
library(igraph)
library(reshape2)
library(adaptMCMC)
library(geoR)