# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mod_cpp <- function(i, n) {
    .Call(`_VEnKF_mod_cpp`, i, n)
}

Wn_Even_Cpp <- function(XX, n, k, N) {
    .Call(`_VEnKF_Wn_Even_Cpp`, XX, n, k, N)
}

XX_Kn_Even_Cpp <- function(XX, n, k, N) {
    .Call(`_VEnKF_XX_Kn_Even_Cpp`, XX, n, k, N)
}

Lorenz04M2Cpp <- function(X0, F_Lor, K_Lor, dt, M, N_Lor) {
    .Call(`_VEnKF_Lorenz04M2Cpp`, X0, F_Lor, K_Lor, dt, M, N_Lor)
}

Lorenz04M2SimCpp <- function(Xinit, F_Lor, K_Lor, dt, M, iter, burn) {
    .Call(`_VEnKF_Lorenz04M2SimCpp`, Xinit, F_Lor, K_Lor, dt, M, iter, burn)
}

