# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A single iteration of the Lorenz 04 model
#'
#' @param XX initial state
#' @param F_Lor F from the Lorenz 04 model
#' @param K_Lor K from the Lorenz 04 model
#' @param dt time step
#' @param M the number of steps that make a time step
#' @param order the order of RK method to use
#' @return dx the increment to reach the new state
#' @export
DeltaLorenz04M2Cpp <- function(X0, F_Lor, K, dt, M, order) {
    .Call('_VEnKF_DeltaLorenz04M2Cpp', PACKAGE = 'VEnKF', X0, F_Lor, K, dt, M, order)
}

#' Simulate from the Lorenz 04 model
#'
#' @param Xinit initial state
#' @param F_Lor F from the Lorenz 04 model
#' @param K_Lor K from the Lorenz 04 model
#' @param dt time step
#' @param M the number of steps that make a time step
#' @param iter number of iterations
#' @param burn how many steps to discard
#' @return Xiter values of all iterations
#' @export
Lorenz04M2SimCpp <- function(Xinit, F_Lor, K_Lor, dt, M, iter, burn, order) {
    .Call('_VEnKF_Lorenz04M2SimCpp', PACKAGE = 'VEnKF', Xinit, F_Lor, K_Lor, dt, M, iter, burn, order)
}

